blueprint:
  name: Inicio diferido
  description: Detecta la mejor franja consecutiva con menor precio PVPC y activa el dispositivo durante esa franja.
  domain: automation
  input:
    pvpc_sensor:
      name: Sensor de precios PVPC
      selector:
        entity:
          filter:
            integration: pvpc_hourly_pricing
    switch_dispositivo:
      name: Dispositivo a controlar
      default: {}
      selector:
        target:
    duracion_horas:
      name: Duración en horas de la franja
      description: Número de horas consecutivas para evaluar y activar el dispositivo
      default: 3
      selector:
        number:
          min: 1
          max: 24
          step: 1
    input_mejor_franja:
      name: Variable para almacenar la hora de inicio
      description: Input_number que recibirá la hora de inicio de la siguiente mejor franja
      selector:
        entity:
          filter:
            domain: input_number
    input_on_before:
      name: Acciones antes de encender el dispositivo
      default: []
      selector:
        action: {}

    input_on_after:
      name: Acciones después de encender el dispositivo
      default: []
      selector:
        action: {}

triggers:
  - trigger: time_pattern
    minutes: 0

action:
  - variables:
      best_start: "{{ states(pvpc_sensor.entity_id) | int }}"
      duracion: !input duracion_horas
      now_hour: "{{ now().hour }}"
  - service: input_number.set_value
    target:
      entity_id: !input input_mejor_franja
    data:
      value: "{{ best_start }}"
  - choose:
      - conditions: >
          {{ now_hour >= best_start and now_hour < (best_start + duracion) }}
        sequence:
          - choose:
              - conditions: "{{ action_on_before is defined }}"
                sequence: !input action_on_before
          - service: switch.turn_on
            target:
              entity_id: !input switch_dispositivo
          - choose:
              - conditions: "{{ action_on_after is defined }}"
                sequence: !input action_on_after

mode: single